project:
  type: website
  output-dir: docs

website:
  title: "Katrina Hirezi"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Marketing Analytics"
        href: marketing-analytics.qmd
      - text: "Résumé"
        href: resume.qmd


format:
  html:
    theme: [flatly, theme.scss]
    toc: true

