---
title: "Résumé"
---

```{r knit-resume, echo=FALSE, message=FALSE}
rmarkdown::render(
  "resume/Resume.Rmd",
  output_format = "pdf_document",
  output_file   = "Resume.pdf",
  output_dir    = "resume",
  quiet         = TRUE
)
```

You can view a PDF version of my résumé [here](resume/Resume.pdf).

# Professional Summary

I'm a third year Marketing student at Cal Poly Pomona. With my degree, I hope to work in promotions, specifically concert promotions. I'm interested in creating immersive brand experiences through concerts and music events. I am currently working for the City of San Dimas in their Parks and Recreation Department.

# Skills

- **Programming Languages:** R 
- **Productivity Tools:** Microsoft Office, Canva, Google Docs, Google Slides, Google Drive 
- **Communication**
- **Trained in first aid**
- **Team Work**
- **Customer Service**

# Education

| Degree                             | Year                          | College / Department                 | Institution         |
| ---------------------------------- | ----------------------------- | ------------------------------------ | ------------------- |
| As-T Business Administration       | 2022 – 2024                   | Business Division                    | Mt. San Antonio College |
| Bachelor in Science Business Administration - Marketing | 2024 - Expected Graduate: 2026| Singelyn Graduate School of Business        | Cal Poly Pomona |

# Work Experience

### Recreation Leader, City of San Dimas: Parks and Recreation  
*June 2024 - Present*

- Responsible for planning, organizing, supervising.
- Provide public engagement and customer service.
- Coordinated and collaborated with other leaders.
- Worked on community programs.

---
